version: '3.7'
name: hairsalon

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongodb_data_container:/data/db"
    networks:
      - hairSalonNet

networks:
  hairSalonNet:
    driver: bridge

volumes:
  mongodb_data_container:
    driver: local