version: '3.7'
name: hairsalon

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongodb_data_container:/data/db"
    networks:
      - hairSalonNet

  redis:
    image: redis
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

networks:
  hairSalonNet:
    driver: bridge

volumes:
  mongodb_data_container:
    driver: local
  redis_data:
    driver: local