package pl.edu.wit.hairsalon.setting.dto;

public enum SettingIdDto {

    SALON_NAME,
    SALON_ADDRESS_STREET_NAME,
    SALON_ADDRESS_STREET_NUMBER,
    SALON_ADDRESS_APARTMENT_NUMBER,
    SALON_ADDRESS_POSTAL_CODE,
    SALON_ADDRESS_CITY,
    SALON_ADDRESS_COUNTRY,
    SALON_CONTACT_PHONE_NUMBER,
    SALON_CONTACT_EMAIL,
    SALON_START_HOUR_WORK,
    SALON_END_HOUR_WORK,
    NOTIFICATIONS_EMAIL_LOGIN,
    NOTIFICATIONS_EMAIL_PASSWORD,
    NOTIFICATIONS_EMAIL_SMTP_HOST,
    NOTIFICATIONS_EMAIL_SMTP_PORT,
    NOTIFICATIONS_EMAIL_REQUIRE_SECURE_CONNECTION,
    NOTIFICATIONS_EMAIL_OUTCOMING,
    NOTIFICATIONS_SMS_API_TOKEN

}
